#!/bin/bash
#Regexp
regexdom="(?=^.{5,254}$)(^(?:(?!\d+\.)[a-zA-Z0-9_\-]{1,63}\.?)+\.(?:[a-z]{2,})$)"

#Vars
checkdig=0;
checkreg=0;
address=$1;

#Regexp
checkreg() {
        if [[ $address =~ $regexdom ]] ;
                then checkreg=1;
        fi
}

#Domain Check
checkdns() {
       [ -z "$(dig +short "$address")" ] 
          checkdig=1
}

#Execute
checkreg;
checkdns;

#Results
if [ $checkreg == 1 ] && [ $checkdig == 1 ];
        then    echo "OK";
        else    echo "NOT";
fi
#End
